// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjWHAyzf2E11lcjs8T1Ft2I-7HNeH94_U',
    appId: '1:828740336591:web:96c9ecea1f8ce321acf0ba',
    messagingSenderId: '828740336591',
    projectId: 'bartender-a2405',
    authDomain: 'bartender-a2405.firebaseapp.com',
    storageBucket: 'bartender-a2405.appspot.com',
    measurementId: 'G-WQBE021EHY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2lQNxhWMabXObqiY54AVcM8bog-xadkA',
    appId: '1:828740336591:android:780923b3ab601afdacf0ba',
    messagingSenderId: '828740336591',
    projectId: 'bartender-a2405',
    storageBucket: 'bartender-a2405.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACqOujV3s2kF8nIaoXEh972R-NtfX8mVA',
    appId: '1:828740336591:ios:51d2b5c20e7d31c7acf0ba',
    messagingSenderId: '828740336591',
    projectId: 'bartender-a2405',
    storageBucket: 'bartender-a2405.appspot.com',
    iosClientId: '828740336591-nrhmpouvvdvue5aodo7omfjaictqgies.apps.googleusercontent.com',
    iosBundleId: 'com.example.bartendersAndMore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACqOujV3s2kF8nIaoXEh972R-NtfX8mVA',
    appId: '1:828740336591:ios:6ef76b5d49154749acf0ba',
    messagingSenderId: '828740336591',
    projectId: 'bartender-a2405',
    storageBucket: 'bartender-a2405.appspot.com',
    iosClientId: '828740336591-2ejhq28tasa8gl3fggqodhjiupl9cui1.apps.googleusercontent.com',
    iosBundleId: 'com.example.bartendersAndMore.RunnerTests',
  );
}
